#ifndef STRLNG_FN_PREPRO_H
#define STRLNG_FN_PREPRO_H

#include "../strlng.h"

void FN_PREPRO_using(STRLNG_FUNCTION_SCOPE*, STRLNG_GLOBAL_SCOPE*);
void FN_PREPRO_rtarg(STRLNG_FUNCTION_SCOPE*, STRLNG_GLOBAL_SCOPE*);
void FN_PREPRO_entry(STRLNG_FUNCTION_SCOPE*, STRLNG_GLOBAL_SCOPE*);
void FN_PREPRO_debug(STRLNG_FUNCTION_SCOPE*, STRLNG_GLOBAL_SCOPE*);
void FN_PREPRO_bufsz(STRLNG_FUNCTION_SCOPE*, STRLNG_GLOBAL_SCOPE*);

#endif //STRLNG_FN_PREPRO_H
